In [2]:
import numpy as np

In [3]:
x_axis_new = np.array([1, 0, 0])
y_axis_new = np.array([0, 1, 0])
z_axis_new = np.array([0, 0, 1])
rotation_matrix = np.array([x_axis_new, y_axis_new, z_axis_new])
print(rotation_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
