In [1]:
import open3d as o3d
import numpy as np

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
def load_point_cloud(local_path, bag_id, pointcloud_name):
    pcd = o3d.io.read_point_cloud(f"{local_path}/bag_{bag_id}/{pointcloud_name}.pcd")
    return pcd
# ply_point_cloud = o3d.data.PLYPointCloud()
# o3d.visualization.draw_geometries([pcd],
#                                   zoom=0.3412,
#                                   front=[0.4257, -0.2125, -0.8795],
#                                   lookat=[2.6172, 2.0475, 1.532],
#                                   up=[-0.0694, -0.9768, 0.2024])

In [8]:
local_path = "D:\Cherry_combined\Cherry Trees\Cherry Trees"
pcd = load_point_cloud(local_path, 0, "bottom_cloud")

In [9]:
print(np.asarray(pcd.points))

[[ 0.39341486 -0.14553139  0.72133231]
 [ 0.39581791 -0.14781585  0.72251111]
 [ 0.39579624 -0.14455284  0.72481942]
 ...
 [ 0.30896685 -0.60596591  2.2330568 ]
 [ 0.30016264 -0.5646829   2.2328606 ]
 [ 0.48306251 -0.43808237  2.2345779 ]]


In [10]:
print(np.asarray(pcd.colors))

# Only when I clear the colors I can see the tree! 
# pcd.colors = o3d.utility.Vector3dVector()

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 ...
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
print(np.asarray(pcd.normals))

[]


In [12]:
o3d.visualization.draw_geometries([pcd],
                                  zoom=0.3412,
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[2.6172, 2.0475, 1.532],
                                  up=[-0.0694, -0.9768, 0.2024])

[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 
