In [8]:
import open3d as o3d
import numpy as np

In [3]:
def load_point_cloud(local_path, bag_id, pointcloud_name):
    pcd = o3d.io.read_point_cloud(f"{local_path}/bag_{bag_id}/{pointcloud_name}.pcd")
    return pcd
# ply_point_cloud = o3d.data.PLYPointCloud()
# o3d.visualization.draw_geometries([pcd],
#                                   zoom=0.3412,
#                                   front=[0.4257, -0.2125, -0.8795],
#                                   lookat=[2.6172, 2.0475, 1.532],
#                                   up=[-0.0694, -0.9768, 0.2024])

In [30]:
local_path = "D:\Cherry_combined\Cherry Trees\Cherry Trees"
pcd = load_point_cloud(local_path, 0, "cloud_final")

In [31]:
print(np.asarray(pcd.points))

[[ 0.12878767 -0.49631402  0.63535219]
 [ 0.12825823 -0.49528104  0.63914973]
 [ 0.12907906 -0.49499035  0.64244044]
 ...
 [ 0.30896685 -0.60596591  2.2330568 ]
 [ 0.30016264 -0.5646829   2.2328606 ]
 [ 0.48306251 -0.43808237  2.2345779 ]]


In [38]:
print(np.asarray(pcd.colors))

# Only when I clear the colors I can see the tree! 
pcd.colors = o3d.utility.Vector3dVector()

[]


In [36]:
print(np.asarray(pcd.normals))

[]


In [37]:
o3d.visualization.draw_geometries([pcd],
                                  zoom=0.3412,
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[2.6172, 2.0475, 1.532],
                                  up=[-0.0694, -0.9768, 0.2024])