In [5]:
import numpy as np
import configparser
import sys

# caution: path[0] is reserved for script path (or '' in REPL)
sys.path.insert(1, '..\src')

from src.super_points import *
from src.helpers import *

In [6]:
x_axis_new = np.array([1, 0, 0])
y_axis_new = np.array([0, 1, 0])
z_axis_new = np.array([0, 0, 1])
rotation_matrix = np.array([x_axis_new, y_axis_new, z_axis_new])
print(rotation_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [9]:
# Load the point cloud
config = configparser.RawConfigParser()
config.read(r"config\config.ini")
local_path = config.get('DATA', 'PATH')

pcd = load_point_cloud(local_path, 0, "cloud_final")

# Load the superpoints
clusters, super_points = get_super_points(get_data(pcd), 0.1)

# Make point cloud out of superpoints
super_points_pcd = numpy_to_pcd(super_points)

# Visualize the point cloud
o3d.visualization.draw_geometries([super_points_pcd],
                                    zoom=0.455,
                                    front=[-0.4999, -0.1659, -0.8499],
                                    lookat=[2.1813, 2.0619, 2.0999],
                                    up=[0.1204, -0.9852, 0.1215])

Calculating super points...
 Points left: 338591


NameError: name 'dist' is not defined